# Generated by Django 5.0.14 on 2026-06-26 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        ("products", "0006_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="cover_image_alt",
            field=models.CharField(
                blank=True,
                help_text="Alt text for featured image.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="faq_json",
            field=models.TextField(
                blank=True, default="[]", help_text="JSON array of FAQ items."
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Pin to homepage hero section."
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_description",
            field=models.CharField(
                blank=True, help_text="Max 160 chars.", max_length=160, null=True
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Falls back to title if empty.",
                max_length=70,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="og_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="quality_score",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0–100 score from Content Quality Engine. Must be ≥80 to publish.",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="related_products",
            field=models.ManyToManyField(
                blank=True, related_name="blog_posts", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="related_services",
            field=models.ManyToManyField(
                blank=True, related_name="blog_posts", to="products.service"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="UTC time for scheduled posts. Displayed as EAT in admin.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="author_name",
            field=models.CharField(
                blank=True,
                help_text="Override display name (used for AI-generated posts).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(help_text="Full HTML article body."),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="excerpt",
            field=models.TextField(
                blank=True,
                help_text="Max 300 chars. Shown on blog cards.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Falls back to cover_image_url if empty.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="reading_time",
            field=models.PositiveIntegerField(
                default=5, help_text="Estimated reading time in minutes."
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(
                help_text="Max 70 chars for SEO. Shown with counter in admin.",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="BlogGenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("scheduler", "Celery Scheduler"),
                            ("admin", "Admin Dashboard"),
                            ("seed", "Deployment Seed"),
                        ],
                        default="admin",
                        max_length=20,
                    ),
                ),
                ("topic_used", models.TextField()),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("quality_score", models.PositiveIntegerField(default=0)),
                ("retries", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retry", "Retried"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_log", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_logs",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
