# Generated by Django 5.0.14 on 2026-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broken_links_count', models.IntegerField(default=0)),
                ('broken_links', models.JSONField(default=list)),
                ('missing_images_count', models.IntegerField(default=0)),
                ('missing_images', models.JSONField(default=list)),
                ('missing_metadata_count', models.IntegerField(default=0)),
                ('missing_metadata', models.JSONField(default=list)),
                ('missing_schema_count', models.IntegerField(default=0)),
                ('missing_schema', models.JSONField(default=list)),
                ('slow_pages_count', models.IntegerField(default=0)),
                ('slow_pages', models.JSONField(default=list)),
                ('redirect_issues_count', models.IntegerField(default=0)),
                ('redirect_issues', models.JSONField(default=list)),
                ('duplicate_content_count', models.IntegerField(default=0)),
                ('duplicate_content', models.JSONField(default=list)),
                ('indexing_problems_count', models.IntegerField(default=0)),
                ('indexing_problems', models.JSONField(default=list)),
                ('overall_score', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(choices=[('chatbot', 'AI Chatbot'), ('product_content', 'Product Content Generation'), ('seo_assistant', 'SEO Assistant'), ('health_assistant', 'Website Health Assistant')], max_length=50)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('response_time', models.DecimalField(decimal_places=4, max_digits=8)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent'], name='monitoring__agent_60e01f_idx'), models.Index(fields=['timestamp'], name='monitoring__timesta_4bc8eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=1000)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time', models.DecimalField(decimal_places=4, max_digits=8)),
                ('success', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['endpoint'], name='monitoring__endpoin_6b8039_idx'), models.Index(fields=['timestamp'], name='monitoring__timesta_bb8179_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=1000)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=20)),
                ('metric_name', models.CharField(choices=[('FCP', 'First Contentful Paint'), ('LCP', 'Largest Contentful Paint'), ('CLS', 'Cumulative Layout Shift'), ('INP', 'Interaction to Next Paint'), ('TTFB', 'Time to First Byte')], max_length=20)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_name'], name='monitoring__metric__9601be_idx'), models.Index(fields=['device'], name='monitoring__device_90869c_idx'), models.Index(fields=['timestamp'], name='monitoring__timesta_20ea4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('failed_login', 'Failed Login Attempt'), ('admin_login', 'Successful Admin Login'), ('suspicious_request', 'Suspicious Request Pattern'), ('blocked_ip', 'IP Address Blocked'), ('rate_limit', 'Rate Limit Exceeded'), ('unauthorized_access', 'Unauthorized Access Attempt')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('details', models.TextField()),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type'], name='monitoring__event_t_cde90c_idx'), models.Index(fields=['timestamp'], name='monitoring__timesta_881349_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('404', '404 Page Not Found'), ('500', '500 Server Error'), ('api', 'API Failure'), ('database', 'Database Failure'), ('auth', 'Authentication Failure'), ('image', 'Image Loading Failure'), ('openai', 'OpenAI API Error'), ('email', 'Email Delivery Error'), ('inventory', 'Inventory Sync Error'), ('cloudinary', 'Cloudinary Upload Error')], default='500', max_length=50)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('affected_page', models.CharField(blank=True, max_length=1000, null=True)),
                ('affected_api', models.CharField(blank=True, max_length=1000, null=True)),
                ('affected_user', models.CharField(blank=True, max_length=255, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['error_type'], name='monitoring__error_t_d3ed5a_idx'), models.Index(fields=['timestamp'], name='monitoring__timesta_f0c9aa_idx')],
            },
        ),
    ]
