# Generated by Django 5.0.14 on 2026-06-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0002_blogpost_cover_image_alt_blogpost_faq_json_and_more"),
        ("products", "0006_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("datasheet", "Product Data Sheet"),
                            ("iso_guide", "ISO Standard Guide"),
                            ("kebs_guide", "KEBS Compliance Guide"),
                            ("iec_guide", "IEC Standard Guide"),
                            ("case_study", "Case Study"),
                            ("whitepaper", "Technical Whitepaper"),
                        ],
                        db_index=True,
                        default="datasheet",
                        max_length=30,
                    ),
                ),
                ("standard_code", models.CharField(blank=True, max_length=80)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.TextField(blank=True, max_length=160)),
                ("excerpt", models.TextField(max_length=300)),
                ("body_html", models.TextField()),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="tech-docs/pdfs/"
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "related_blogs",
                    models.ManyToManyField(
                        blank=True, related_name="technical_docs", to="blog.blogpost"
                    ),
                ),
                (
                    "related_products",
                    models.ManyToManyField(
                        blank=True, related_name="technical_docs", to="products.product"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
