# Generated by Django 5.0.14 on 2026-07-13 10:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0007_product_is_watermark_applied_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WatermarkSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watermark_enabled", models.BooleanField(default=False)),
                ("right_click_protection_enabled", models.BooleanField(default=False)),
                ("drag_protection_enabled", models.BooleanField(default=False)),
                ("long_press_protection_enabled", models.BooleanField(default=False)),
                ("seo_metadata_protection_enabled", models.BooleanField(default=False)),
                (
                    "watermark_text",
                    models.CharField(
                        blank=True,
                        default="Finstar Industrial Chemicals",
                        max_length=120,
                    ),
                ),
                (
                    "watermark_secondary_text",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "watermark_opacity",
                    models.PositiveSmallIntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("watermark_font_size", models.PositiveSmallIntegerField(default=32)),
                (
                    "watermark_angle",
                    models.SmallIntegerField(
                        default=-30,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "watermark_position",
                    models.CharField(
                        choices=[
                            ("center", "Center (single stamp)"),
                            ("tiled", "Tiled (repeated diagonal pattern)"),
                        ],
                        default="tiled",
                        max_length=10,
                    ),
                ),
                ("watermark_color", models.CharField(default="#FFFFFF", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Watermark settings",
                "verbose_name_plural": "Watermark settings",
            },
        ),
        migrations.CreateModel(
            name="WatermarkBatch",
            fields=[
                (
                    "batch_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("all", "All active products"),
                            ("category", "By category"),
                            ("tag", "By tag"),
                            ("never_protected", "Never protected yet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scope_value",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("apply", "Apply watermark"),
                            ("restore", "Restore original"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("total_matched", models.PositiveIntegerField(default=0)),
                ("queued_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="watermark_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WatermarkJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("apply", "Apply watermark"),
                            ("restore", "Restore original"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("next_attempt_at", models.DateTimeField(auto_now_add=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="watermark.watermarkbatch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watermark_jobs",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="watermark_w_status_c53b2d_idx",
                    ),
                    models.Index(
                        fields=["batch", "status"],
                        name="watermark_w_batch_i_083b10_idx",
                    ),
                ],
            },
        ),
    ]
