# Generated by Django 5.0.14 on 2026-05-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(choices=[('contact_form', 'Contact Form'), ('quote_request', 'Quote Request'), ('chatbot', 'Chatbot'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone Call'), ('other', 'Other')], default='other', max_length=30)),
                ('source_page', models.CharField(blank=True, max_length=500, null=True)),
                ('referrer', models.CharField(blank=True, max_length=1000, null=True)),
                ('quote_request_id', models.IntegerField(blank=True, null=True)),
                ('contact_message_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
