# Generated by Django 5.0.14 on 2026-05-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(help_text='Page path or identifier, e.g. "home", "/products/acetone"', max_length=500, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=500, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.CharField(blank=True, max_length=500, null=True)),
                ('og_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords', null=True)),
                ('canonical_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('structured_data', models.JSONField(blank=True, help_text='Raw JSON-LD structured data object', null=True)),
                ('robots', models.CharField(default='index, follow', help_text='Robots meta tag value', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Page',
                'verbose_name_plural': 'SEO Pages',
                'ordering': ['page'],
            },
        ),
    ]
