# Generated by Django 5.0.14 on 2026-05-26 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('applications', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('industries_served', models.TextField(blank=True, null=True)),
                ('faqs', models.TextField(blank=True, null=True)),
                ('cas_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='CAS Number')),
                ('chemical_formula', models.CharField(blank=True, max_length=100, null=True)),
                ('purity', models.CharField(blank=True, max_length=100, null=True)),
                ('appearance', models.CharField(blank=True, max_length=255, null=True)),
                ('density', models.CharField(blank=True, max_length=100, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('packaging_type', models.CharField(blank=True, max_length=100, null=True)),
                ('pricing', models.CharField(blank=True, max_length=255, null=True)),
                ('min_order_quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit_of_measure', models.CharField(default='KG', max_length=50)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('cloudinary_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=125, null=True)),
                ('image_title', models.CharField(blank=True, max_length=125, null=True)),
                ('image_caption', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=160, null=True)),
                ('seo_keywords', models.TextField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=95, null=True)),
                ('og_description', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_description', models.CharField(blank=True, max_length=200, null=True)),
                ('schema_markup', models.TextField(blank=True, null=True)),
                ('whatsapp_template', models.TextField(blank=True, null=True)),
                ('quotation_template', models.TextField(blank=True, null=True)),
                ('cta_content', models.CharField(blank=True, max_length=255, null=True)),
                ('hazard_classification', models.TextField(blank=True, null=True, verbose_name='Hazard Identification / PPE rules')),
                ('status', models.CharField(choices=[('active', 'Active / Available'), ('draft', 'Draft'), ('scheduled', 'Scheduled'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='products.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
