# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_seo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='og_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='og_description',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='twitter_description',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
