# Generated by Django 5.0.14 on 2026-07-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_watermark_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="last_restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="watermark_applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
